export const ANHLIYSKA_MOVA = 'Англійська мова';
export const FIZKULTURA = 'Фізкультура';
export const INFORMATYKA = 'Інформатика';
export const KHOREOHRAFIYA = 'Хореографія';
export const KHRYSTYYANSKA_ETYKA = 'Християнська етика';
export const MATEMATYKA = 'Математика';
export const MUZYKA = 'Музика';
export const OBRAZOTVORCHE = 'Образотворче мистецтво';
export const UKRAYINSKA_MOVA = 'Українська мова';
export const YA_DOSLIDZHUYU_SVIT = 'Я досліджую світ';
export const YADS_PRYRODA = 'ЯДС (природа)';
export const YADS_TRUD_NAV = 'ЯДС (труд. нав.)';
export const YADS_UKRAYINSKA_MOVA = 'ЯДС (українська мова)';
export const YADS_MATEMATYKA = 'ЯДС (математика)';

export const ZARUBIZHNA_LITERATURA = 'Зарубіжна Література';
export const PIZNAYEMO_PRYRODU = 'Пізнаємо природу';
export const ROBOTOTEKHNIKA = 'Робототехніка';
export const ETYKA = 'Етика';
export const ZDOROVYA_BEZPEKA_DOBROBUT = "Здоров'я, безпека, добробут";
export const NIMETSKA_MOVA = 'Німецька мова';
export const VSTUP_DO_ISTORIYI = 'Вступ до історії';
export const TEKHNOLOHIYI = 'Технології';
export const UKRAYINSKA_LITERATURA = 'Українська література'